database:
  dbhost: "db"
  dbport: "5432"
  dbuser: "postgres"
  dbpassword: "123456789"
  dbdatabase: "Avito-back"

server:
  shost: ""
  sport: "8080"

jwt:
  tokenExpiryHours: 1
  secret: "123456765432345"