database:
  dbhost: "localhost"
  dbport: "5432"
  dbuser: "postgres"
  dbpassword: "123456789"
  dbdatabase: "Avito-back"

server:
  shost: "localhost"
  sport: "8081"

jwt:
  tokenExpiryHours: 1
  secret: "123456765432345"