version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=123456789
      - DB_NAME=Avito-back
      - JWT_SECRET=123456765432345
    networks:
      - back-tier
    depends_on:
      - db
    restart: always
  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_DB=Avito-back
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - back-tier
    restart: always

networks:
  back-tier:
    name: back-tier

volumes:
  db_data: